address = bytes
hash = bytes

asset = {
    policy: bytes
    name: bytes
}

pool-redeemer = #6.0(apply-pool) / #6.1(update-fee) / #6.2(withdraw-liquidity-share)

apply-pool = {
    apBatcherAddress: address
    apLicenseIndex: int
}

update-fee = {
    uftOwnerIndex: int
}

withdraw-liquidity-share = {
    wlsOwnerIndex: int
    wslFeeToIndex: int
}